name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.3.0
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Electron build
        run: pnpm build

      - name: Electron release
        run: pnpm release
